### ISSUE TITLE
runProducer.sh needs -Dexec.cleanupDaemonThreads=false

### ISSUE THREAD

**Issue by trbryant2** [ibm-cloud-architecture/refarch-mq-messaging#1]
The runProducer.sh script causes exceptions due to background threads still remaining active in the MQ classes.  You need to add 

-Dexec.cleanupDaemonThreads=false

to the end of the command in the script to enable a clean shutdown of the application.

**Comment by jbcodeforce** [comment]
Thank you. I updated the 2 scripts.
